server:
  port: 9999
service-url:
  user-service: http://localhost:3344
spring:
  application:
    name: spring-cloud-Gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  gateway:
    routes:
      - id: path_route #路由的ID
        uri: ${service-url.user-service}/test/test4 #匹配后路由地址
        predicates: # 断言，路径相匹配的进行路由
          - Path=/test/test4